void systick1Us();
void systickUs(int delay);
void systick1Ms(int time);
void systickDelaySeconds(int delay);
void blinkBlue(int ct);
void blinkRed(int ct);
void blinkGreen(int ct);
void moveForward(void);
void moveBackwards(void);
void pwmGeneratorLeft(int duty);
void pwmGeneratorRight(int duty);
void glowGreen();
void glowRed();
